Full version
chumaachike/financial-data pull request #1
Opened 2022-07-25 13:53 UTC by chumaachike

Created a financial times app that takes all the stock in an API and renders them as a button then on click would show the income statement of the specific stock

2022-07-25 15:14 UTC, ShoiraTa requested changes
Hi @chumaachike ,

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

**First let me to point out:**

- Project is properly deployed  ✔️ 
- You passed all the Linters! ✔️ 
- Professional pull request! ✔️ 

Keep on coding, good job so far! :clap:

There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

 ## Required Changes  :recycle: 

- [ ] Kindly try to write meaningful commits, and to commit frequently, I can see only 7 `Removing limit`

- [ ] Check more comments under the review.

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear by mentioning my Github username.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-25 15:14 UTC, ShoiraTa commented on src/Components/CompanyListContainer.jsx
> +  const allCompanies = useSelector((state) => state.AllCompanies).slice(0, 1000);
- [ ]  The Home page should have a list  of categories that could be filtered using given parameters, e.g. category name. Kindly add filtering function.

2022-07-25 15:14 UTC, ShoiraTa commented on src/Components/CompanyListContainer.jsx
> +    </div>
- [ ] It is important to follow the  [design guidelines](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)) including:

* Typography: font face, size, and weight
* Layout: composition and space between elements.

- [ ] Kindly make sure to have the same layout, and typography:

### Homepage:

Wireframe design  | Your  design
------------- | -------------
<img width="200" alt="Screenshot 2022-07-25 at 19 04 35" src="https://user-images.githubusercontent.com/77038610/180810391-e4d6db80-dba9-478d-b9eb-62d9941b86e4.png"> | <img width="375" alt="Screenshot 2022-07-25 at 19 04 17" src="https://user-images.githubusercontent.com/77038610/180810279-81ab19da-aa72-426b-9f30-b5a9a712fe50.png">

### Details page:

Wireframe design  | Your  design
------------- | -------------
<img width="197" alt="Screenshot 2022-07-25 at 19 05 25" src="https://user-images.githubusercontent.com/77038610/180810749-29839e63-459d-4a07-988f-195d3730be05.png"> | <img width="377" alt="Screenshot 2022-07-25 at 19 05 44" src="https://user-images.githubusercontent.com/77038610/180810902-534aa040-cd2d-4620-83ec-8d7e15ef6c68.png">

2022-07-25 15:14 UTC, ShoiraTa commented on src/Components/__tests__/CompanyList.test.js
> +};
- [ ] Kindly add unit tests for several components of the app and some pure functions in Redux code.
- [ ] Existing tests do run properly, kindly run tests and make sure they show green, currently test result is `2 files obsolete`:
<img width="623" alt="Screenshot 2022-07-25 at 19 10 14" src="https://user-images.githubusercontent.com/77038610/180812645-df3f69cd-1415-4c35-b4eb-0242e007b5a2.png">

2022-07-25 17:42 UTC, chumaachike commented on src/Components/CompanyListContainer.jsx
> +  const allCompanies = useSelector((state) => state.AllCompanies).slice(0, 1000);
HI, Please I am confused. When you say categories, what kind of categories are we talking about

2022-07-25 18:01 UTC, ShoiraTa commented on src/Components/CompanyListContainer.jsx
> +  const allCompanies = useSelector((state) => state.AllCompanies).slice(0, 1000);
Hi, 
Categories was an example, sorting criteria depends on you, the main idea is implement a filter. You can sort by stock names. When users input `GOOGL` it should sort and show `GOOGL`  stock

2022-07-27 03:46 UTC, Mihndim2020 approved these changes
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi @chumaachike, 

### Good job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Clean/Organized code
:heavy_check_mark:  Good commit messages
:heavy_check_mark: Descriptive Readme file

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-27 03:46 UTC, Mihndim2020 commented on src/redux/Exchange/Exchange.js
> +/* eslint-disable default-param-last */
- [OPTIONAL] `Linters` are tools that perform static analysis on software in order to recognize and report adherence/non-adherence to some set of coding best practice.Instead of disabling `eslint`, it will be nice to fix the issue.

2022-07-27 03:46 UTC, Mihndim2020 commented on src/redux/CompanyDetails/CompanyDetail.js
> +/* eslint-disable default-param-last */
- [OPTIONAL] `Linters` are tools that perform static analysis on software in order to recognize and report adherence/non-adherence to some set of coding best practice.Instead of disabling `eslint`, it will be nice to fix the issue.

2022-07-27 03:46 UTC, Mihndim2020 commented on src/redux/Allcompanies/Allcompanies.js
> +/* eslint-disable default-param-last */
- [OPTIONAL] `Linters` are tools that perform static analysis on software in order to recognize and report adherence/non-adherence to some set of coding best practice.Instead of disabling `eslint`, it will be nice to fix the issue.

2022-07-27 10:58 UTC, merged